import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Herosection from "@/components/herosection";
import Plan from "@/components/plan";
import Footer from "@/components/footer";
import Contact from "@/components/contact";
import Services from "@/components/services";
import Exercise from "@/components/exercise";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {/* <Herosection />
        <Services/>
        <Plan />
        <Exercise />
        <Contact/> */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}
